### ISSUE TITLE
Features - Database

### ISSUE THREAD

**Issue by at-vietpham** [AT-PHPIntership/food-drink#1]
@at-dungle, @at-thaitran @at-sonle 
Mọi người cập nhật Requiment và Database vào issue này như hôm qua anh có nói nghe.

**Comment by at-sonle** [comment]
[shopdatabase.pdf](https://github.com/AT-PHPIntership/food-drink/files/1990400/shopdatabase.pdf)

**Comment by at-vietpham** [comment]
@at-sonle Copy text + dùng markdown cho dễ đọc đi em.

**Comment by at-sonle** [comment]
![databaseshop](https://user-images.githubusercontent.com/37792504/39852728-4418f932-5448-11e8-82ec-210fb343c340.png)

**Comment by at-sonle** [comment]
SHOP FRUITS AND DRINKS

	1. Database And Template
	    .Create Database
	    .Add Template

	2. Admin And User
	    .Sign In 
  	    .Register
	    .Log Out
	
	3. User
	    .View Profile
	    .Update Profile
 	    .Product Slider
  	    .Hot trend
	    .Top Rate
	    .Filter Product
	    		-Alphabet
			-Price
			-Category 
			-Rating 
			-Orde
	    .Cart
			-Add Cart
			-Edit Cart
			-Checkout Cart
			-Remove Products From Cart
	    .CheckOut
			-View List Products
			-View Status Of Order 
			-If Order Has not accepted User Can Delete it 
			-View History Orders
	    .Product
			-Detail Product
			-View Products Through Category
	    .Comment Each Product
	    .Review Each Product

	4.Admin
	    .CRUD User
	    .CRUD Category
	    .CRUD Product
	    .CRUD Order
	    .View And Delete Review
	    .Statistic Product

**Comment by at-sonle** [comment]
## SHOP FRUITS AND DRINKS

1. Database And Template
   - Create Database
   - Add Template

2. Admin And Users
   - Sign In 
   - Register
   - Log Out
	
3. User
   - View Profile
   - Update Profile
   - Product Slider
   - Hot trend
   - Top Rate
   - Filter Product
     - Alphabet
     - Price
     - Category
     - Rating 
     - Top Products By Order
   - Cart
     - Add Cart
     - Edit Cart
     - Checkout Cart
     - Remove Products From Cart
   - CheckOut
     - View List Products
     - View Status Of Order 
     - If Order Has not been accepted User Can Delete it 
     - View History Orders
   - Product
     - Detail Product
     - View Products Through Category
   - Comment Each Product
   - Review Each Product
     
4. Admin
   - CRUD User
   - CRUD Category
   - CRUD Product
   - CRUD Order
   - View And Delete Post
   - Statistic Product

**Comment by ml-thinh-nguyen** [comment]
LGTM
